// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default FirebaseOptions configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUeUVUYbp4fZP6OCpBn6rt0R3f6IN1LdI',
    appId: '1:477566770667:web:0fc883805901cfe1724dae',
    messagingSenderId: '477566770667',
    projectId: 'duezy-91ea2',
    authDomain: 'duezy-91ea2.firebaseapp.com',
    storageBucket: 'duezy-91ea2.firebasestorage.app',
    measurementId: 'G-E1LK8C8PX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcc0YxJmTN2gLJ2k3iWr5NCG_VLJQx0o',
    appId: '1:477566770667:android:f128401b533a3462724dae',
    messagingSenderId: '477566770667',
    projectId: 'duezy-91ea2',
    storageBucket: 'duezy-91ea2.firebasestorage.app',
  );
}
